import { Car } from './types';

export const CARS: Car[] = [
  {
    id: '1',
    brand: 'Mercedes-Benz', model: 'GLE Coupe', year: 2024, price: 125000,
    engine: '3.0L V6 Turbo', mileage: 0, transmission: 'Automática',
    image: 'https://images.unsplash.com/photo-1636510856336-f19cada6f03b?q=80&w=1170&auto=format&fit=crop',
    category: 'SUV', bodyType: 'SUV Coupe', color: 'Negro', fuelType: 'Híbrido', featured: true,
    description: 'El equilibrio perfecto entre deportividad y elegancia. Un SUV de lujo con tecnología de vanguardia.',
    images: [
      'https://images.unsplash.com/photo-1636510856336-f19cada6f03b?q=80&w=1170&auto=format&fit=crop',
      'https://cdn.motor1.com/images/mgl/z2mo6/s3/mercedes-amg-gle-63-s-coupe.jpg',
    ],
    version: 'AMG Line 450d', doors: 5, power: '367 hp', traction: '4MATIC', capacity: 5,
    negotiable: true, acceptsTrade: true, plateLastDigit: '2', plateType: 'Par',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: true, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: true,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '2',
    brand: 'Porsche', model: '911 Carrera', year: 2023, price: 145000,
    engine: '3.0L Flat-6 Twin-Turbo', mileage: 5200, transmission: 'Automática',
    image: 'https://hips.hearstapps.com/hmg-prod/images/porsche-carrera-s-2025-6-677f954d171e8.jpg?crop=0.733xw:0.869xh;0.0737xw,0.131xh&resize=980:*',
    category: 'Deportivo', bodyType: 'Coupe', color: 'Gris', fuelType: 'Gasolina',
    description: 'Icono de la ingeniería alemana. Rendimiento puro y diseño atemporal.',
    images: [
      'https://hips.hearstapps.com/hmg-prod/images/porsche-carrera-s-2025-6-677f954d171e8.jpg?crop=0.733xw:0.869xh;0.0737xw,0.131xh&resize=980:*',
      'https://www.topgear.com/sites/default/files/2025/01/CZ26W03OX0005_RGB_2.jpg',
    ],
    version: 'Carrera S PDK', doors: 2, power: '450 hp', traction: 'RWD', capacity: 2,
    negotiable: false, acceptsTrade: false, plateLastDigit: '7', plateType: 'Impar',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: false, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: false,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '3',
    brand: 'Audi', model: 'RS e-tron GT', year: 2024, price: 160000,
    engine: 'Eléctrico (590 HP)', mileage: 0, transmission: 'Automática',
    image: 'https://images.unsplash.com/photo-1655126275641-21e114342284?q=80&w=1170&auto=format&fit=crop',
    category: 'Lujo', bodyType: 'Sedán', color: 'Azul', fuelType: 'Eléctrico', featured: true,
    description: 'El futuro de la movilidad eléctrica. Potencia silenciosa y lujo sostenible.',
    images: [
      'https://images.unsplash.com/photo-1655126275641-21e114342284?q=80&w=1170&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1654853976163-7ecedd0dd4d3?q=80&w=1170&auto=format&fit=crop',
    ],
    version: 'RS e-tron GT quattro', doors: 4, power: '590 hp', traction: 'quattro AWD', capacity: 5,
    negotiable: true, acceptsTrade: true, plateLastDigit: '0', plateType: 'Par',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: true, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: true,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '4',
    brand: 'BMW', model: 'X7 M60i', year: 2024, price: 115000,
    engine: '4.4L V8 M TwinPower', mileage: 0, transmission: 'Automática',
    image: 'https://http2.mlstatic.com/D_Q_NP_2X_742564-MCO105902813049_012026-T.webp',
    category: 'SUV', bodyType: 'SUV', color: 'Blanco', fuelType: 'Gasolina',
    description: 'Presencia imponente y confort sin igual para toda la familia.',
    images: [
      'https://http2.mlstatic.com/D_Q_NP_2X_742564-MCO105902813049_012026-T.webp',
      'https://carsales.pxcrush.net/carsales/cars/private/b18iysdaxbs6c4kqah3lvj35i.jpg?pxc_method=fitfill&pxc_bgtype=self&pxc_size=720,480',
    ],
    version: 'M60i xDrive', doors: 5, power: '530 hp', traction: 'xDrive AWD', capacity: 7,
    negotiable: true, acceptsTrade: true, plateLastDigit: '4', plateType: 'Par',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: true, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: true,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '5',
    brand: 'Mercedes-Benz', model: 'S-Class', year: 2024, price: 135000,
    engine: '3.0L I6 Turbo', mileage: 0, transmission: 'Automática',
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/55/Mercedes-Benz_W223_IMG_6663.jpg',
    category: 'Lujo', bodyType: 'Sedán', color: 'Negro', fuelType: 'Gasolina',
    description: 'El pináculo del lujo automotriz. Confort insuperable y tecnología de vanguardia.',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/5/55/Mercedes-Benz_W223_IMG_6663.jpg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlzXPiUfd1iEvXiMzunpjcNwifHU5T0flDNw&s',
    ],
    version: 'S 500 AMG Line', doors: 4, power: '435 hp', traction: '4MATIC', capacity: 5,
    negotiable: false, acceptsTrade: false, plateLastDigit: '6', plateType: 'Par',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: true, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: true,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '6',
    brand: 'Porsche', model: 'Taycan Turbo S', year: 2024, price: 185000,
    engine: 'Eléctrico (750 HP)', mileage: 0, transmission: 'Automática',
    image: 'https://www.elcarrocolombiano.com/wp-content/uploads/2020/07/20200710-PORSCHE-TAYCAN-ELECTRICO-COLOMBIA-PRECIO-VERSIONES-CARACTERISTICAS-02.jpg',
    category: 'Deportivo', bodyType: 'Sedán', color: 'Azul', fuelType: 'Eléctrico',
    description: 'Electrizante en todos los sentidos. El deportivo eléctrico que redefine el rendimiento.',
    images: [
      'https://www.elcarrocolombiano.com/wp-content/uploads/2020/07/20200710-PORSCHE-TAYCAN-ELECTRICO-COLOMBIA-PRECIO-VERSIONES-CARACTERISTICAS-02.jpg',
      'https://a.storyblok.com/f/322327/1700x1300/6ee174f235/ta26q3eid0006-taycan-turbo-s-cockpit-myt.jpg/m/990x673/smart/filters:format(webp)',
    ],
    version: 'Turbo S Cross Turismo', doors: 4, power: '750 hp', traction: 'AWD', capacity: 4,
    negotiable: true, acceptsTrade: false, plateLastDigit: '1', plateType: 'Impar',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: true, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: false,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '7',
    brand: 'Land Rover', model: 'Range Rover Sport', year: 2024, price: 130000,
    engine: '3.0L I6 MHEV', mileage: 0, transmission: 'Automática',
    image: 'https://http2.mlstatic.com/D_Q_NP_2X_982532-MCO108380631452_032026-T.webp',
    category: 'SUV', bodyType: 'SUV', color: 'Gris', fuelType: 'Híbrido', featured: true,
    description: 'Lujo sin límites, dentro y fuera de la carretera. El SUV más refinado del mundo.',
    images: [
      'https://http2.mlstatic.com/D_Q_NP_2X_982532-MCO108380631452_032026-T.webp',
      'https://http2.mlstatic.com/D_Q_NP_2X_994103-MCO109286327681_032026-T.webp',
    ],
    version: 'P400 HSE Dynamic', doors: 5, power: '400 hp', traction: '4WD', capacity: 5,
    negotiable: true, acceptsTrade: true, plateLastDigit: '8', plateType: 'Par',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: true, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: true,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '13',
    brand: 'Audi', model: 'A4 Sedan', year: 2024, price: 45000,
    engine: '2.0L I4 Turbo', mileage: 0, transmission: 'Automática',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyArTb3OtwrK_jqz-AdjurO14PYelGzDPOiA&s',
    category: 'Lujo', bodyType: 'Sedán', color: 'Blanco', fuelType: 'Gasolina',
    description: 'Sofisticación y eficiencia en un sedán compacto de lujo.',
    images: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyArTb3OtwrK_jqz-AdjurO14PYelGzDPOiA&s',
      'https://acnews.blob.core.windows.net/imgnews/paragraph/NPAZ_ee68a4e2df02404e9a1ec59e15016e04.jpg',
    ],
    version: '40 TFSI S Line', doors: 4, power: '190 hp', traction: 'FWD', capacity: 5,
    negotiable: true, acceptsTrade: true, plateLastDigit: '3', plateType: 'Impar',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: false, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: false,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '8',
    brand: 'Tesla', model: 'Model S Plaid', year: 2024, price: 110000,
    engine: 'Tri-Motor Eléctrico (1020 HP)', mileage: 0, transmission: 'Automática',
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=1000',
    category: 'Lujo', bodyType: 'Sedán', color: 'Rojo', fuelType: 'Eléctrico',
    description: 'Aceleración más allá de lo imaginable. El futuro de los sedanes de alto rendimiento.',
    images: [
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1536700503339-1e4b06520771?auto=format&fit=crop&q=80&w=1000',
    ],
    version: 'Plaid Tri-Motor', doors: 4, power: '1020 hp', traction: 'AWD', capacity: 5,
    negotiable: false, acceptsTrade: false, plateLastDigit: '5', plateType: 'Impar',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: true, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: true,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '9',
    brand: 'Audi', model: 'R8 V10 Performance', year: 2023, price: 210000,
    engine: '5.2L V10 FSI', mileage: 1200, transmission: 'Automática',
    image: 'https://www.topgear.com/sites/default/files/images/cars-road-test/2019/03/e826efae20bd5b2ec17a3036a69ba465/audiuk00021489.jpg',
    category: 'Deportivo', bodyType: 'Coupe', color: 'Amarillo', fuelType: 'Gasolina', featured: true,
    description: 'Nacido en la pista, construido para la carretera. El superdeportivo definitivo de Audi.',
    images: [
      'https://www.topgear.com/sites/default/files/images/cars-road-test/2019/03/e826efae20bd5b2ec17a3036a69ba465/audiuk00021489.jpg',
      'https://www.topgear.com/sites/default/files/images/cars-road-test/2019/03/e826efae20bd5b2ec17a3036a69ba465/audiuk00021489.jpg',
    ],
    version: 'V10 Performance quattro', doors: 2, power: '620 hp', traction: 'quattro AWD', capacity: 2,
    negotiable: false, acceptsTrade: false, plateLastDigit: '9', plateType: 'Impar',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: false, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: false, airConditioning: true, electricWindows: true, rainSensor: false,
    steeringWheelControls: true, cupHolder: false, autoWindowClose: false, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: false,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '10',
    brand: 'BMW', model: 'M4 Competition', year: 2024, price: 95000,
    engine: '3.0L I6 Twin-Turbo', mileage: 0, transmission: 'Automática',
    image: 'https://http2.mlstatic.com/D_Q_NP_2X_880628-MCO107856982174_032026-T.webp',
    category: 'Deportivo', bodyType: 'Coupe', color: 'Verde', fuelType: 'Gasolina',
    description: 'Agilidad pura y potencia brutal. El referente de los coupés deportivos.',
    images: [
      'https://http2.mlstatic.com/D_Q_NP_2X_880628-MCO107856982174_032026-T.webp',
      'https://autos93.com/cdn/shop/files/79C4A19B-27AF-435D-B8A0-422762FAB833.jpg?v=1730386562&width=1946',
    ],
    version: 'M4 Competition xDrive', doors: 2, power: '510 hp', traction: 'xDrive AWD', capacity: 4,
    negotiable: true, acceptsTrade: true, plateLastDigit: '2', plateType: 'Par',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: false, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: false,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '11',
    brand: 'Mercedes-Benz', model: 'G-Class G63 AMG', year: 2024, price: 220000,
    engine: '4.0L V8 Biturbo', mileage: 0, transmission: 'Automática',
    image: 'https://http2.mlstatic.com/D_Q_NP_2X_999271-MCO107519898849_022026-T.webp',
    category: 'SUV', bodyType: 'SUV', color: 'Negro Mate', fuelType: 'Gasolina', featured: true,
    description: 'La leyenda todoterreno. Lujo inquebrantable y potencia sin límites.',
    images: [
      'https://http2.mlstatic.com/D_Q_NP_2X_999271-MCO107519898849_022026-T.webp',
      'https://http2.mlstatic.com/D_Q_NP_2X_680366-MCO105095369790_012026-T.webp',
    ],
    version: 'AMG G 63', doors: 5, power: '585 hp', traction: '4MATIC AWD', capacity: 5,
    negotiable: false, acceptsTrade: false, plateLastDigit: '0', plateType: 'Par',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: false, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: false,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
  {
    id: '12',
    brand: 'Porsche', model: 'Cayenne Turbo GT', year: 2024, price: 195000,
    engine: '4.0L V8 Biturbo', mileage: 0, transmission: 'Automática',
    image: 'https://www.alainclass.com/wp-content/uploads/2024/07/2024-Porsche-Cayenne-Turbo-GT-Black-3405-8.jpg',
    category: 'SUV', bodyType: 'SUV', color: 'Gris Crayón', fuelType: 'Gasolina',
    description: 'El SUV que se siente como un deportivo. Rendimiento extremo en cada curva.',
    images: [
      'https://www.alainclass.com/wp-content/uploads/2024/07/2024-Porsche-Cayenne-Turbo-GT-Black-3405-8.jpg',
      'https://hips.hearstapps.com/hmg-prod/images/239548-5040x3362-6464ac4db0bf9.jpg',
    ],
    version: 'Turbo GT Coupe', doors: 5, power: '660 hp', traction: 'AWD', capacity: 5,
    negotiable: true, acceptsTrade: true, plateLastDigit: '6', plateType: 'Par',
    abs: true, airbagDriver: true, airbagPassenger: true, stabilityControl: true,
    parkingSensor: true, reverseCamera: true, automaticLights: true, rearFogLights: true,
    rearDefogger: true, centralLocking: true, thirdBrakeLightLed: true,
    autopilot: false, airConditioning: true, electricWindows: true, rainSensor: true,
    steeringWheelControls: true, cupHolder: true, autoWindowClose: true, boardComputer: true, lightsOnAlert: true,
    steering: 'Electroasistida', alarm: true,
    alloyWheels: true, sunroof: true,
    amFm: true, auxInput: true, bluetooth: true, mp3: true, usbInput: true,
    leatherSeats: true,
  },
];

export const BLOG_POSTS = [
  {
    id: '1',
    title: 'Mantenimiento preventivo para autos de lujo',
    excerpt: 'Descubre los secretos para mantener tu vehículo premium en condiciones óptimas.',
    date: '15 Mar 2024',
    image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    title: 'Guía de compra: ¿SUV o Sedán?',
    excerpt: 'Analizamos cuál es la mejor opción según tu estilo de vida y necesidades.',
    date: '10 Mar 2024',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800',
  },
];
